package keepinchecker.database;

import static org.junit.Assert.*;

import java.util.ArrayList;
import java.util.Arrays;

import org.junit.Test;

import keepinchecker.database.entity.User;
import keepinchecker.setup.KeepInCheckerTestCase;

public class UserManagerTest extends KeepInCheckerTestCase {
	
	private UserManager userManager;
	
	@Test
	public void testSaveGetUser() throws Exception {
		userManager = new UserManager();
		
		User user = new User();
		user.setUserName("TestUser");
		user.setUserEmail("test@example.com");
		user.setUserEmailPassword("password");
		user.setPartnerEmails(new ArrayList<>(Arrays.asList("test1@example.com", "test2@example.com")));
		user.setEmailFrequency(User.EMAIL_FREQUENCY_DAILY);
		user.setEmailLastSentDate(123456789);
		
		userManager.saveUser(user);
		User userFromDb = userManager.getUser();
		
		assertEquals("User ID should have been autogenerated and saved to the database", 1, userFromDb.getUserId());
		assertEquals("User name should have been saved to the database", "TestUser", userFromDb.getUserName());
		assertEquals("User email should have been saved to the database", "test@example.com", userFromDb.getUserEmail());
		assertEquals("User email password should have been saved to the database", "password", userFromDb.getUserEmailPassword());
		assertEquals("Partner emails should have been saved to the database", 2, userFromDb.getPartnerEmails().size());		
		assertTrue("Partner emails should have been saved to the database", 
				userFromDb.getPartnerEmails().containsAll(new ArrayList<>(Arrays.asList("test1@example.com", "test2@example.com"))));
		assertEquals("Email frequency should have been saved to the database", User.EMAIL_FREQUENCY_DAILY, userFromDb.getEmailFrequency());
		assertEquals("Email last sent date should have been saved to the database", 123456789, userFromDb.getEmailLastSentDate());
	}

}
